### ISSUE TITLE
Error when trying to plot one cachefile

### ISSUE THREAD

**Issue by BettinaTrunk** [neuromti/tool-offspect#48]
When plotting one cachefile (AmWo post5 ipsilesional, can be found here: /mnt/data/data08/ProcessedData/2020_Stroke_Maps/cachefiles_inspected/AmWo/post5), I get the following error:

```
Traceback (most recent call last):
  File "plotmaps.py", line 47, in <module>
    plot_map([cachefile1])
  File "C:\tool-offspect\offspect\cache\plot.py", line 330, in plot_map
    return plot_glass(coords, values, **kwargs)
  File "C:\tool-offspect\offspect\cache\plot.py", line 152, in plot_glass
    filled_img = project_into_nifti(coords, values, smooth)
  File "C:\tool-offspect\offspect\cache\plot.py", line 73, in project_into_nifti
    apos = pinv(affine).dot(list(chain(pos, [1])))
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'
```

For all other cachefiles that are already inspected, no errors occur. 
Offspect is up to date.

**Comment by agricolab** [comment]
Trace number 183 has [None, None, None] as coords. Additionally, I changed `plot_map` so it will plot even if some traces have unusable coordinates. It will log this, though.
``` bash
This plot is based on 183/183 traces.
  0 traces were rejected.
  1 traces were not inspected.
  2 values were ignored because their coords are outside of the plot
  1 coordinates from traces [183] could not be used
  1 times, 4 values were projected on a single voxel.
  4 times, 3 values were projected on a single voxel.
 16 times, 2 values were projected on a single voxel.
```
